---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
  annotations:
    service.beta.kubernetes.io/vpsie-lb-protocol: "http"
    service.beta.kubernetes.io/vpsie-resource-identifier: "8152952c-87ca-11eb-9353-0242ac110004"
    service.beta.kubernetes.io/vpsie-cookie-name : "vpsie-cookie"
    service.beta.kubernetes.io/vpsie-cookie-check : "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP