apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
          name: http-web-svc


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vpsie-lb-protocol: "tcp"
    service.beta.kubernetes.io/vpsie-resource-identifier: "8152952c-87ca-11eb-9353-0242ac110004"
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: http-web-svc