---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
  annotations:
    service.beta.kubernetes.io/vpsie-lb-protocol: "tcp" # tcp is the default value
    service.beta.kubernetes.io/vpsie-loadbalancer-plan: "basic"  # basic, standard, professional (basic is the default value)
    service.beta.kubernetes.io/vpsie-private-loadbalancer: true
    service.beta.kubernetes.io/vpsie-vpc-id: 1233 # vpc id

spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP