---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
  namespace: storage
  annotations:
    service.beta.kubernetes.io/vpsie-lb-protocol: "tcp" # tcp is the default value
    service.beta.kubernetes.io/vpsie-loadbalancer-plan: "basic"  # basic, standard, professional (basic is the default value)
    service.beta.kubernetes.io/vpsie-resource-identifier: "8152952c-87ca-11eb-9353-0242ac110004"
spec:
  type: LoadBalancer
  selector:
    app: nfs-server
  ports:
    - name: first
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: second
      protocol: TCP
      port: 111
      targetPort: 111
    - name: third
      protocol: TCP
      port: 20048
      targetPort: 20048